spring:
  application:
    name: greenting-service
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
erudio-config-server:
  greenting: "Wello"
  default-value: "World!"